#!/bin/bash

# TODO: consider bundling bloop with fury instead of depending on an installed one?
PATH="${PATH}:${HOME}/.bloop"

TEST_SUITE=$(dirname $(readlink -f "$0"))

export TESTROOTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

verify_command(){
    if ! type "$1" >/dev/null 2>&1
    then
        echo "command: $1 is not set" && exit 1
    fi
}

run_test_suite(){
    local failed_test_cases=""
    local passed_test_cases=""
    for test_case in $TEST_SUITE/*/
    do
        [ -d "${test_case}" ] && \
            echo "verifying: $(basename ${test_case})"
	if run_test_case ${test_case}; then
	    passed_test_cases="$passed_test_cases ${test_case}"
	else
	    failed_test_cases="$failed_test_cases ${test_case}"
	fi
    done
    echo "=========================================="
    echo "Passed: $(echo ${passed_test_cases} | wc -w)"
    echo "Failed: $(echo ${failed_test_cases} | wc -w)"
    [ -z "${failed_test_cases}" ] && echo "SUCCESS" || \
        (echo "FAILURE in test cases:" && echo "${failed_test_cases}" && exit 1)
}

remove_empty_file(){
    local file=$1
    [ ! -s "${file}" ] && rm "${file}"
}

run_test_case(){
    local test_case=$1
    local name=$(basename ${test_case})
    local test_dir=$(mktemp -d /tmp/fury_verification_${name}-XXXXXXXX)
    local logs="${test_dir}/logs.txt"
    local errors="${test_dir}/errors.txt"

    (cp -r "${test_case}/." "${test_dir}" && \
        cd ${test_dir} && \
        bash -c "${test_case}/run.sh" || \
	(cat ./.fury/logs/* && exit 1)
    )
}


source ~/.bashrc
verify_command "fury"
verify_command "bloop"
verify_command "blp-server"

run_test_suite

