#!/bin/bash

SCALA=$(coursier fetch --classpath org.scala-lang:scala-reflect:2.12.8 com.facebook:nailgun-server:1.0.0)
bloop_pid_file="$HOME/bloop_pid"

bloop_is_running(){
    bloop about > /dev/null 2>&1
}

wait_for_bloop(){
    for x in $(seq 1 20); do
        if bloop about > /dev/null 2>&1 ; then
            return $ans
        fi
        sleep 0.1
    done
    echo "Bloop server not running" > /dev/stdout
    exit 1
}


stop_bloop(){
    if [ -f "${bloop_pid_file}" ]
    then
        echo "terminating $(cat "${bloop_pid_file}")" && \
            kill "$(cat ${bloop_pid_file})" && rm "${bloop_pid_file}"
    fi
}

start_bloop(){
    stop_bloop
    blp-server &
    echo $! > "${bloop_pid_file}"
    wait_for_bloop
}

function assert_equal {
    ACTUAL=$2
    EXPECTED=$1

    if [ "$ACTUAL" !=  "$EXPECTED" ]; then
	file=${BASH_SOURCE[1]##*/} line=${BASH_LINENO[0]}
	echo "$file:$line: assertion failed"
	echo "'$OUTPUT' != '$EXPECTED'"
	exit 1
    fi
}
