pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - "status-success=build (ubuntu-latest)"
      - "base=master"
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
