steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'fury/ci', '.']
  timeout: 600s
  id: 'build'

- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-u', 'bash_user', '-w', '/home/bash_user', '-t', 'fury/ci', '/integration']
  timeout: 600s
  id: 'integration'

- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-w', '/build', '-t', 'fury/ci', 'make', 'test']
  timeout: 400s
  id: 'unittests'

options:
  machineType: 'N1_HIGHCPU_8'

timeout: 1000s
