#!/bin/bash
#
# This is the Fury launcher script, which will download and run Fury in "standalone" mode

version="v0.8.2-29-g9109b6f"
ipfsHash="QmSZTTohbDe3fLKjakRrRAa3Qbw7yRt1XbeTWpMaA4GMUc"
startTime="$(($(date "+%s%N")/1000000))"
xdgUsrHome="${XDG_DATA_HOME:-"$HOME/.local/share"}"
xdgSysHome="${XDG_DATA_HOME:-/usr/share}"
xdgHome="$([ "$EUID" = "0" ] && echo "${xdgSysHome}" || echo "${xdgUsrHome}")"
furyDir="${xdgHome}/fury"
furyUsr="${furyDir}/usr"
currentDir="${furyUsr}/current"
installedVersion="$(cat "${currentDir}/.version" 2> /dev/null || echo "")"
downloadDir="${furyDir}/downloads"
downloadFile="${downloadDir}/fury-${version}.tar.gz"
ipfsGateway="https://gateway.pinata.cloud/ipfs"
downloadUrl="${ipfsGateway}/${ipfsHash}"
installDir="${furyUsr}/$([ "${installedVersion}" = "${version}" ] && echo "current" || echo "${version}")"
args="$@"

stderrEcho() {
  printf "$1\n" >&2
}

fail() {
  message="$1"
  stderrEcho "${message}" && exit 1
}

downloadFuryTar() {
  mkdir -p "${downloadDir}"
  stderrEcho "Downloading Fury ${version}"

  [ -f "${downloadFile}" ] || \
      curl -# -Lso "${downloadFile}" "${downloadUrl}" || \
      fail "Could not download Fury version ${version}"

  stderrEcho "Download complete"
}

untarFury() {
  stderrEcho "Extracting Fury ${version} into ${installDir}"
  mkdir -p "${installDir}" && \
      tar xf "${downloadFile}" -C "${installDir}" || \
      fail "Could not extract Fury"
}

installFury() {
  [ "${currentVersion}" = "${version}" ] || \
      (downloadFuryTar && untarFury)
}

runFury() {
  FURY_HOME="${installDir}" START_TIME="${startTime}" \
      "${installDir}/bin/fury" standalone ${args}
}

([ -d "${installDir}" ] || installFury) && runFury
