#!/bin/sh

PORT="8462"
CLASSPATH="$FURYHOME/lib/fury-menu.jar:$FURYHOME/lib/nailgun-server-0.9.1.jar:$FURYHOME/lib/jna-4.5.1.jar:$FURYHOME/lib/directory-watcher-0.8.0.jar"
MAIN="com.martiansoftware.nailgun.NGServer"

startFury() {
  nohup $FURYHOME/bin/scala -cp "$CLASSPATH" "$MAIN" $PORT &> /dev/null &
  local RUNNING='0'
  printf 'Fury daemon is starting'
  for I in $(seq 1 25); do
    fury help > /dev/null 2> /dev/null && RUNNING='1';
    if [ "$RUNNING" -eq '1' ]; then
      printf 'done\n'
      exit 0
    fi
    printf '.'
    sleep 0.15
  done
  printf '\n'
  printf 'Starting Fury is taking longer than expected.\n'
}

case "$1" in
  "start")
    startFury
    ;;
  "stop")
    ng --nailgun-port "$PORT" ng-stop &> /dev/null
    printf 'Fury daemon has shut down.\n'
    ;;
  "restart")
    fury stop && fury start
    ;;
  "prompt")
    ng --nailgun-port "$PORT" "fury.Main" $@ 2> /dev/null || printf " \e[0;30m[ ]"
    ;;
  "completion")
    ng --nailgun-port "$PORT" "fury.Main" $@ 2> /dev/null || \
      printf "1:Command:((start:'start the Fury daemon'))\n"
    ;;
  *)
    ng --nailgun-port "$PORT" "fury.Main" $@
    ;;
esac

