#!/bin/sh

if test -f "layer.fury"; then
  HASH=$(sha256sum layer.fury | head -c64)
  cp layer.fury "$HOME/.furyrc/layers/$HASH"
  echo "layerRef	$HASH" > .focus.fury
  echo "path	." >> .focus.fury
else
  echo "layer.fury not found"
fi
