#!/bin/sh

rootdir=$(git rev-parse --show-toplevel)

files=$(git diff --diff-filter=d --name-only HEAD  | grep -E "[.]scala$")
if [ -z "$files" ]; then
    exit 0
fi

if ! command -v scalafmt > /dev/null 2>&1; then
   echo "scalafmt not found in PATH. Install it from 'https://scalameta.org/scalafmt/docs/installation.html'"
   exit 1
fi

if scalafmt --quiet --test --non-interactive $files; then
    exit 0
else
    echo ""
    echo "==========================================================================="
    echo "Scala files not formatted with scalafmt. "
    echo "Please run 'scalafmt $rootdir/src'q"
    echo "==========================================================================="
    exit 1
fi
