#!/bin/bash

DIR="$1"
TEST="$2"
TMPDIR=".${TEST}.tmp"
BASE="$PWD"
RED=$(printf '\e[31m')
GREEN=$(printf '\e[32m')
RESET=$(printf '\e[0m')

echo ""
echo "----------------------------------------------------------------------------------------------------"
echo " Running test ${TEST}"
echo "----------------------------------------------------------------------------------------------------"

rm -fr "$TMPDIR"
cp -r "$DIR/$TEST" "$TMPDIR"
cd "$TMPDIR"
set -v
source ./script 2>&1 | tee output
set +v

echo "----------------------------------------------------------------------------------------------------"
diff output check
SUCCESS=$?
[ $SUCCESS = 0 ] && echo " [${GREEN}PASS${RESET}] ${TEST}" && rm -f "../$TEST.log" || (
    echo "----------------------------------------------------------------------------------------------------"
    echo " [${RED}FAIL${RESET}] ${TEST}" && mv output "../$TEST.log"
  )
echo "----------------------------------------------------------------------------------------------------"
cd "$BASE"
rm -fr "$TMPDIR"
exit $SUCCESS
