#!/bin/bash

SCALA_VERSION="2.12.8"
NAILGUN_VERSION="1.0.0"

resolveScala() {
  message "Resolving Scala ${SCALA_VERSION}"
  ${FURYHOME}/bin/coursier fetch --classpath "org.scala-lang:scala-reflect:${SCALA_VERSION}" "com.facebook:nailgun-server:${NAILGUN_VERSION}" > ${FURYHOME}/classpath
}

doInstall() {
  message "Removing old version of Fury"
  rm ${FURYHOME}/bin/* ${FURYHOME}/lib/* ${FURYHOME}/etc/* ${FURYHOME}/classpath
  message "Installing new version of Fury"
  mv ${FURYHOME}/upgrade/* ${FURYHOME}/
  rmdir ${FURYHOME}/upgrade
}

doInstall && resolveScala
