export PATH=$PATH:$FURYHOME/bin:$FURYHOME/usr
export fpath=($FURYHOME/etc/completion/zsh $fpath)
autoload -U +X compinit && compinit

if [ -z "${XDG_CONFIG_HOME}" ]
then
  CONFIG="${HOME}/.config/fury"
else
  CONFIG="${XDG_CONFIG_HOME}/fury"
fi

source ${CONFIG}/aliases
